# Generated by Django 5.2.1 on 2025-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_option_question_quiz_resulttip_delete_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
