# Generated by Django 5.2.1 on 2025-07-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_quiz_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulttip',
            old_name='tip',
            new_name='title',
        ),
    ]
