# Generated by Django 5.2.1 on 2025-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_tip_resulttip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resulttip',
            name='do',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resulttip',
            name='dont',
            field=models.TextField(blank=True),
        ),
    ]
