# Generated by Django 5.2.1 on 2025-07-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_resulttip_description_alter_resulttip_do_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
    ]
